# Generated by Django 5.0.4 on 2024-04-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_alter_usermodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='gender',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=30),
        ),
    ]
