# Generated by Django 5.0.4 on 2024-04-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0005_alter_usermodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=30),
        ),
    ]
